name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Capture Version with Dry Run
        id: capture_version
        run: |
          version=$(npx semantic-release --dry-run | grep -oP '(?<=The next release version is )\d+\.\d+\.\d+' || echo "versión desconocida")
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "::set-output name=version::$version"

      - name: Run Semantic Release
        if: steps.capture_version.outputs.version != 'versión desconocida'
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = process.env.VERSION || 'versión desconocida';
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              labels: "release-failed"
            });

            const issueTitle = `Error en el release de la versión ${version}`;
            const issueExists = issues.some(issue => issue.title === issueTitle);

            if (!issueExists) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: `⚠️ **Se produjo un error durante el proceso de release**.\n\n` +
                      `Detalles del error:\n\n` +
                      `- Versión: ${version}\n` +
                      `- Usuario que ejecutó: ${{ github.actor }}\n\n` +
                      `Por favor, revisa los logs para más detalles.`,
                labels: ["release-failed", "bug"]
              });
            }
