name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create Issue on Failure
        if: failure() && steps.semantic_release.outcome != 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = "${{ steps.semantic_release.outputs.version || 'versión desconocida' }}";
            const user = "${{ github.actor }}";
            const errorDetails = `⚠️ **Error en el proceso de release** para la versión ${version}.\n\n` +
                                 `Detalles del error:\n\n` +
                                 `- Fecha: ${new Date().toISOString()}\n` +
                                 `- Usuario que ejecutó el release: ${user}\n\n` +
                                 `Por favor, revisa el pipeline para ver el error completo y tomar las acciones necesarias.`;
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Error en el release de la versión ${version}`,
              body: errorDetails,
              labels: ["release-failed", "bug"]
            })
      
